/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package release.myPlugin.DataBase2

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'release.myPlugin.DataBase2.greeting' plugin.
 */
class ReleaseMyPluginDataBase2PluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("release.myPlugin.DataBase2.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }
}
