/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package by.vorobey.plugin

import org.gradle.testfixtures.ProjectBuilder
import org.gradle.api.Project
import spock.lang.Specification

/**
 * A simple unit test for the 'by.vorobey.plugin.greeting' plugin.
 */
class ReleaseMyPluginPluginTest extends Specification {
    /*def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("by.vorobey.plugin.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }*/
}
