/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package release.myPlugin.DataBase2

import org.gradle.api.Project
import org.gradle.api.Plugin
import release.myPlugin.DataBase2.tasks.CreateTable
import release.myPlugin.DataBase2.tasks.DropTable
import release.myPlugin.DataBase2.tasks.InsertTable

/**
 * A simple 'hello world' plugin.
 */
class ReleaseMyPluginDataBase2Plugin implements Plugin<Project> {
    void apply(Project project) {
        // Register a task
        project.tasks.register("greeting") {
            doLast {
                println("Hello from plugin 'release.myPlugin.DataBase2.greeting'")
            }
        }

        project.tasks.register("CreateTable", CreateTable) {
            setGroup("dataBase")
        }

        project.tasks.register("InsertTable", InsertTable) {
            setGroup("dataBase")
        }

        project.tasks.register("DropTable", DropTable) {
            setGroup("dataBase")
        }

    }
}
